#pragma once

#include <QByteArray>
#include <QDateTime>
#include <QHashFunctions>
#include <QJsonObject>
#include <QMetaType>
#include <QString>
#include <memory>

struct PetRecordKey {
  QString account;
  quint64 epoch = 0;
  qint64 instanceId = 0;
  // Memory facts version, independent from ordered Storage write revisions.
  quint64 detailMemoryRevision = 0;
  bool operator==(const PetRecordKey& other) const {
    return account == other.account && epoch == other.epoch && instanceId == other.instanceId &&
           detailMemoryRevision == other.detailMemoryRevision;
  }
  bool operator!=(const PetRecordKey& other) const { return !(*this == other); }
};
inline size_t qHash(const PetRecordKey& key, size_t seed = 0) noexcept {
  return qHashMulti(seed, key.account, key.epoch, key.instanceId, key.detailMemoryRevision);
}

struct RawPetRecordPayload {
  // Member order destroys JSON before releasing its byte-accounting lease.
  std::shared_ptr<void> memoryRetention;
  QJsonObject object;
  quint64 chargedBytes = 0;
private:
  friend class PetRecordCache;
  std::shared_ptr<void> cacheOwner_;
};

struct RawPetRecord {
  PetRecordKey key;
  // Digest of the durable source file as reported by Storage IO. Empty until
  // an actual digest is known; never generated by Core serializing this JSON.
  QByteArray contentDigest;
  bool sourceKnown = false;
  bool complete = false;
  bool persisted = false;
  // Frozen small observation overlay used to form calculation input. This is
  // not another full detail tree; it excludes large relation/backpack arrays.
  QJsonObject brief;
  // A persistent index bound only to contentDigest is valid only in this case.
  bool rawProjectionOnly = true;
  QDateTime observedAt;
  std::shared_ptr<const RawPetRecordPayload> payload;
  const QJsonObject& object() const {
    static const QJsonObject empty;
    return payload ? payload->object : empty;
  }
};
using RawPetRecordHandle = std::shared_ptr<const RawPetRecord>;

struct PetRecordVersion {
  PetRecordKey key;
  QByteArray contentDigest;
  QJsonObject brief;
  bool sourceKnown = false;
  bool complete = false;
  bool resident = false;
  bool persisted = false;
  bool derived = false;
  bool rawProjectionOnly = true;
  QDateTime observedAt;
  bool valid() const { return key.instanceId > 0 && key.detailMemoryRevision != 0; }
};

struct PetRecordCacheStats {
  quint64 chargedBytes = 0; // Includes leases held after LRU eviction/account switch.
  quint64 peakChargedBytes = 0;
  quint64 residentBytes = 0;
  quint64 retainedPayloads = 0;
  int residentRecords = 0;
  int protectedRecords = 0;
  quint64 evictedRecords = 0;
  quint64 refusedRecords = 0;
  // Legacy naked QJsonObject exports are deliberately reported as untracked;
  // callers must carry RawPetRecordHandle to make their lifetime measurable.
  quint64 untrackedExports = 0;
};

Q_DECLARE_METATYPE(PetRecordKey)
Q_DECLARE_METATYPE(RawPetRecordHandle)
Q_DECLARE_METATYPE(PetRecordVersion)
Q_DECLARE_METATYPE(PetRecordCacheStats)
